apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: skillpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dev7878/skillpulse-frontend:2c7d8f775b27500aaa5ff988591cd58d5df4ffab
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 60m
              memory: 32Mi
            limits:
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: skillpulse
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  template:
    spec:
      containers:
        - image: dev7878/skillpulse-frontend:2c7d8f775b27500aaa5ff988591cd58d5df4ffab
